services:
  mlflow:
    build:
      context: ./MLflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./MLflow:/app
    networks:
      - ml-network

  bentoml:
    build: ./bentoML
    container_name: bentoml
    ports:
      - "3000:3000"
    environment:
      - BENTOML_HOME=/app/bentoml_home
    volumes:
      - ./bentoML:/app
      - bentoml_data:/app/bentoml_home
    depends_on:
      - mlflow
    networks:
      - ml-network

  mindsdb:
    image: mindsdb/mindsdb
    container_name: mindsdb
    ports:
      - "47334:47334"
    volumes:
      - mindsdb_data:/root/mindsdb
    networks:
      - ml-network

volumes:
  mindsdb_data:
  bentoml_data:  # Ajoutez cette ligne !

networks:
  ml-network:
    driver: bridge