version: '3.8'

services:
  flowise:
    image: flowiseai/flowise:3.0.4
    container_name: flowise
    ports:
      - "3000:3000"
    environment:
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin123
      - FLOWISE_SECRETKEY=supersecretkey
    volumes:
      - ./data/flowise:/root/.flowise
      - ./flowise-flows:/app/flows
    restart: unless-stopped
    networks:
      - employe_network

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    restart: unless-stopped
    networks:
      - employe_network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - GENERIC_TIMEZONE=Africa/Nairobi
      - EXECUTIONS_PROCESS=main
      - N8N_PERSONALIZATION_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - employe_network

volumes:
  n8n_data:

networks:
  employe_network:
    driver: bridge
